### ISSUE TITLE
Encoding of example formula

### ISSUE THREAD

**Issue by jaanos** [RokIvansek/SAT-solver#1]
Most programs (including your own) have trouble reading your example CNF formula when running on a Linux machine with the UTF-8 default encoding. It seems that the problem is the `×` character in the second line of `19x19queens.txt`. Instead of bothering everyone to fix such a technicality, I'd like to ask you to replace the character with something else (say, `x`), so that the file will not contain any non-ASCII characters.

**Comment by adolenc** [comment]
Sorry, I forgot to double check everything works on Linux. You are right, replacing that character does the trick.
